SKIP_SCHEMAS = {"INFORMATION_SCHEMA"}

DEFAULT_MIG_DB = "MIGRATION_DB"
DEFAULT_MIG_SCHEMA = "PUBLIC"
DEFAULT_STAGE = "MIGRATION_STAGE"
DEFAULT_INTEGRATION = "AZURE_MIGRATION_INT"

DEFAULT_NB_INT_STAGE = "NB_MIG_INT_STAGE"

DEFAULT_LOCAL_INT_STAGE = "LOCAL_BACKUP_STAGE"
